nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    forced_ssl:
        enabled: '%force_ssl%'
        hosts: '%forced_ssl_hosts%'
        hsts_max_age: 31104000 # 1y
    csp:
        enabled: true
        report_logger_service: logger
        hosts: []
        content_types: []
        enforce:
            browser_adaptive:
                enabled: false
            default-src:
                - 'self'
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'https://cdn.jsdelivr.net/'
                - 'https://www.google.com/recaptcha/api.js'
                - 'https://www.gstatic.com/recaptcha/'
            connect-src:
                - 'self'
                - 'https://*.algolia.net'
                - 'https://*.algolianet.com'
            img-src:
                - 'self'
                - 'https:'
                - 'data:'
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://cdn.jsdelivr.net/'
            font-src:
                - 'self'
            frame-src:
                - 'https://www.google.com/recaptcha/'
            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
